app:
  name: webserver
  version: 0.1.0
  env: base
  tcp-timeout-in-seconds: 5
  protocol-test-server-address: localhost:42069

http:
  port: 42069
  prefix: "/"
  ip: 0.0.0.0
  timeout: 5
  cors:
    origins:
      - "https://*"
      - "http://*"
    methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    headers:
      - "Accept"
      - "Authorization"
      - "Content-Type"
      - "X-CSRF-Token"

opentelemetry:
  enabled: false
  endpoint: localhost:4317
  insecure: true
  interval: 20
  metrics:
    interval: 60
    timeout: 30
  traces:
    timeout: 30
    samplerate: 1
    batchsize: 512
    maxqueuesize: 1024
  logs:
    timeout: 30
    batchsize: 512
    maxqueuesize: 2048
    interval: 30
