version: "3"

tasks:
  proto:gen:
    desc: Generate Go code from proto files
    cmd: protoc --go_out=protogenerated --go_opt=module=github.com/taldoflemis/triprotocol-benchmark/protogenerated --go-grpc_out=. --go-grpc_opt=module=github.com/taldoflemis/triprotocol-benchmark/protogenerated ./proto/*.proto -I ./proto/
