version: "3"

tasks:
  proto:gen:
    desc: Generate Go code from proto files
    cmd: protoc --go_out=protogenerated --go_opt=module=github.com/taldoflemis/triprotocol-benchmark/protogenerated --go-grpc_out=. --go-grpc_opt=module=github.com/taldoflemis/triprotocol-benchmark/protogenerated ./proto/*.proto -I ./proto/
  proto:gen-python:
    desc: Generate Python code from proto files
    cmd: protoc --python_out=scripts --pyi_out=scripts ./proto/*.proto -I ./proto/
  benchmark:
    desc: Run benchmark
    cmd: go test -bench . | vizb -o output.html --group-pattern "name/workload/subject" -n "Protocol Comparison Benchmarks" -d "Comparing different protocol manipulation for serialization and deserialization"
